### ISSUE TITLE
clarify reason to add reverse Squid proxy to Stratum 1

### ISSUE THREAD

**Issue by boegel** [cvmfs-contrib/cvmfs-tutorial-2021#12]
We're currently setting up a Squid proxy on the Stratum 1 server, as is recommended at https://cvmfs.readthedocs.io/en/stable/cpt-replica.html#recommended-setup, but we don't mention why we're doing this.

The docs mention:

* reduce points of failure: that's not entirely clear to me... I guess it helps a little when CVMFS itself would die on Stratum 1?
* caching of Geo API calls (are we actually doing this in the current configuration?)
* anything else?

cc @jblomer, @rptaylor

**Comment by jblomer** [comment]
The main point, I think, is that you can eventually scale-out and install multiple squid frontends as the load grows.  Of course in HEP we also already have all the tooling around squids (monitoring, etc.), which is a plus.  Let me invite @DrDaveD for further comments.

**Comment by DrDaveD** [comment]
The doc says "run it on the same machine as Apache to reduce the number of points of failure".  If it is run on a separate machine, then there are two different machines, either of which could cause the service to fail.  So it's not a point about why to run the squid, it's a point about why to have it on the same machine.

The doc doesn't give reasons to have the squid, maybe it should.  The main general reason is for caching the geo api.  In addition, for those stratum 1s that are related to the WLCG, it is helpful for joining monitoring on http://wlcg-squid-monitor.cern.ch.  Those are the main two reasons.

I was about to submit a PR for that doc today because NIKHEF pointed out that it says squid should listen on port 80, but generally it can't do that because it runs as an unprivileged user.  We instead forward port 80 with iptables.   I will include a few other improvements while I'm at it.

I have more complete documentation for setting up a frontend squid using frontier-squid at https://opensciencegrid.org/docs/other/install-cvmfs-stratum1.

**Comment by rptaylor** [comment]
Okay, caching the geo API I can see as a reason (to be weighed against the minor cost of maintaining and configuring another application on the server, and a small amount of extra processing/memory use/latency ).

I'm also curious about the DNS lookups: "A Stratum 1 does a lot of DNS lookups" I don't see how that would be needed to serve data downloads; is that also due to the GeoAPI?

**Comment by DrDaveD** [comment]
Yes, that section on DNS lookups is because of the geo API.  However, I believe the issue is not as severe as it used to be because the geo API now caches all of its lookups for 5 minutes.  It's still probably good advice to maintain a local DNS cache however.  I will expand that section while I'm modifying the doc.
