### ISSUE TITLE
verifying client configuration

### ISSUE THREAD

**Issue by boegel** [cvmfs-contrib/cvmfs-tutorial-2021#13]
As discussed in #9, we should outline how to verify that the client is correctly configured, i.e. that is:

* Actually talking to Stratum 1 (not Stratum 0, as it was initially set up)
* That it is using the proxy server (client access seems to be possible even if the proxy server isn't actually working at all?)

@jblomer Any suggestions here?

See also https://github.com/cvmfs-contrib/cvmfs-tutorial-2021/pull/9#issuecomment-764457005

**Comment by jblomer** [comment]
If `DIRECT` is not part of `CVMFS_HTTP_PROXY`, the client needs to use the configured one.  If this local proxy is not available, the default configuration for cern.ch, egi.eu, hsf.org, and opensciencegrid.org will use centrally provided "fallback proxies". Otherwise, the client might still mount the repository from its local cache.

You can see in `cvmfs_config stat -v <reponame>` which is the active stratum 1 and proxy.

**Comment by bedroge** [comment]
With that command I do indeed get `(offline)` for my non-existing proxy, thanks @jblomer. Let's include that command in the tutorial.

**Comment by rptaylor** [comment]
While `cvmfs_config stat -v` is useful to confirm which proxy is being used, I think you would also still want 
`cvmfs_config chksetup` , to test accessing all stratum servers via all proxies (every permutation).
The latter is a simple quick diagnostic to check all is well while the former is a nice way to explicitly see which proxy is used.

**Comment by bedroge** [comment]
We did already mention `chksetup` in the debugging section of the Advanced topics page, but it may be useful to also mention this in the client config part.
